#!/usr/bin/env python
import os
from balsam.core.models import ApplicationDefinition as App

here = os.path.dirname(os.path.abspath(__file__))
corr_path = '../../software/xpcs-eigen/build/corr'
corr_path = os.path.abspath(os.path.join(here, corr_path))
assert os.path.isfile(corr_path)

corr = App(
    name = 'corr',
    executable = corr_path,
)

APPS = [corr]
for app in APPS:
    if not App.objects.filter(name=app.name).exists():
        app.save()
        print(f"Created app {app.name} in DB")
    else:
        existing_app = App.objects.get(name=app.name)
        existing_app.executable = app.executable
        existing_app.postprocess = app.postprocess
        existing_app.preprocess = app.preprocess
        if hasattr(app, "envscript"):
            existing_app.envscript = app.envscript
        existing_app.save()
        print(f"Updated App {app.name} in DB")

