#!/usr/bin/env python
import argparse
import glob
import getpass
import json
import time
import subprocess
import os
import sys
import pexpect
from add_dag import add_dag

def connect(thetahost, thetaport):
    uname = getpass.getuser()
    ps_check = subprocess.run(
         f'ps aux | grep {uname} | grep "ssh -f -N -L {thetaport}" | grep -v grep',
         stdout=subprocess.PIPE,
         stderr=subprocess.STDOUT,
         shell=True,
         encoding="utf-8",
    )
    if thetahost in ps_check.stdout:
        print("Detected already-running SSH tunnel:\n", ps_check.stdout.strip())
        return

    print("Please authenticate to Theta.")
    X = getpass.getpass('Password: ')
    cmd = f"ssh -f -N -L {thetaport}:localhost:{thetaport} {uname}@{thetahost}.alcf.anl.gov"
    tunnel = pexpect.spawn(cmd)
    tunnel.expect('Password:')
    time.sleep(0.1)
    tunnel.sendline(X)
    time.sleep(0.1)
    return tunnel

parser = argparse.ArgumentParser()
parser.add_argument('--db', required=True, help="path to directory containing server-info")
parser.add_argument('--images', required=True, help="path to directory of .tif images")
parser.add_argument('--destination', required=True, help="where to send data on Theta")
args = parser.parse_args()
args.db = os.path.abspath(os.path.expanduser(args.db))
args.images = os.path.abspath(os.path.expanduser(args.images))
args.destination = os.path.abspath(os.path.expanduser(args.destination))

# load db/server-info
assert os.path.isdir(args.db)
info_path = os.path.join(args.db, 'server-info')
assert os.path.isfile(info_path)
with open(info_path) as fp: info = json.load(fp)
assert os.path.isdir(args.images)
assert len(glob.glob(os.path.join(args.images, '*.tif'))) >= 2

# modify host; export BALSAM_DB_PATH
thetaport = info["port"]
thetahost = info.get("thetahost", info["host"])
info["thetahost"] = thetahost
info["host"] = "localhost"
with open(info_path, 'w') as fp: fp.write(json.dumps(info))
os.environ['BALSAM_DB_PATH'] = os.path.abspath(args.db)

# create SSH background tunnel
tunnel = connect(thetahost, thetaport)

print("Running App sanity check...")
# sanity check balsam ls apps
from balsam.core.models import ApplicationDefinition as App
required_apps = ["find_rst", "register", "align"]
found_apps = []
for app in App.objects.all():
    print(app)
    found_apps.append(app.name)
assert all(app in found_apps for app in required_apps)
print(f"Got all required apps ({required_apps}): OK!")

# Transfer images
print("Transferring images...")
uname = getpass.getuser()
transfer_proc = subprocess.Popen(f'scp -r {args.images} {uname}@{thetahost}.alcf.anl.gov:{args.destination}', shell=True)
print("Waiting on scp to finish...")
retcode = transfer_proc.wait()
print(f"SCP Done: return code {retcode}")
if retcode != 0:
    print("Transfer did not succeed.")
    sys.exit(1)

# create DAG for images/
images_basename = os.path.basename(args.images)
image_dir_on_theta = os.path.join(args.destination, images_basename)
print("Adding DAG to Balsam DB")
jobs = add_dag(image_dir_on_theta)
